### ISSUE TITLE
Facet

### ISSUE THREAD

**Issue by bitbreakr** [PrinceCornNM/ember-algolia#5]
Do you guys have a way of faceting the search?

**Comment by conradlz** [comment]
Yes, you can use the [facets](https://www.algolia.com/doc/api-reference/api-parameters/facets/) parameter in search.

**Comment by bitbreakr** [comment]
Thanks for you help, it worked.

**Comment by conradlz** [comment]
You need to specify a property facets on the object you pass to the search function params.
something like:
`search({indexName: "<indexName>", query: "<query>"}, { facets: [] }, callback);`

**Comment by bitbreakr** [comment]
I made it work

**Comment by bitbreakr** [comment]
I made it work, thanks a lot
